dask_cluster_kwargs:
  account: m4632
  queue_name: premium
  n_nodes: 1
  n_tasks_per_node: 128
  wallclock: 06:00:00
  scheduler_file: null

notebooks:
  - title: C-SON Skill Assessment
    use_dask_cluster: false
    name: cson-skill-assessment
    description: "C-SON Skill Assessment"
    children:
    - compare-to-glodap.ipynb:
      parameters:
        domain_name: "CCS-12km"
        model_files: null
      output_path: executed/papermill/compare-to-glodap_CCS-12km.ipynb